### PR TITLE
Update project_list.txt to include RABA-KGZ import project

### PR DESCRIPTION
**Pull request by stefanb**
Added RABA-KGZ import project
https://wiki.openstreetmap.org/wiki/Slovenia_Landcover_Import_-_RABA-KGZ

### CODE REVIEW

**Comment by stefanb** [comment]
Thanks! 

https://taginfo.openstreetmap.org/sources
if I understand correctly, this project would be visible tomorrow morning?

**Comment by joto** [comment]
@stefanb Yes, it should be.

**Comment by stefanb** [comment]
sources were refreshed as expected, but the newly added project is still missing:
https://taginfo.openstreetmap.org/projects
did it go wrong somewhere?

**Comment by joto** [comment]
Probably a caching issue. The project is there.
https://taginfo.openstreetmap.org/projects/raba_kgz_import

**Comment by stefanb** [comment]
Thanks!

**Comment by stefanb** [comment]
Yesterday i updated the json at http://raba.openstreetmap.si/taginfo.json
and the project is now gone from the project list https://taginfo.openstreetmap.org/projects
Only the direct link is available: https://taginfo.openstreetmap.org/projects/raba_kgz_import
but it shows no data.

Full changelog is available at https://github.com/openstreetmap-si/raba.openstreetmap.si/commits/master/taginfo.json for comparisment

Any idea what might be wrong with the new json? Syntay seems valid according to jsonlint.com

**Comment by joto** [comment]
Probably the byte order marker at the beginning of the file. Please convert to UTF-8.

**Comment by stefanb** [comment]
Fixed and updated on the website: http://raba.openstreetmap.si/taginfo.json

**Comment by stefanb** [comment]
Now the project JSON got read by taginfo.

Interestingly,
https://taginfo.openstreetmap.org/keys/raba%3Aid#values
got no new description from JSON, but has only those from OSM wiki
but tags from JSON are visible here:
https://taginfo.openstreetmap.org/tags/raba%3Aid=1800#projects

Is it
* Some cachig issue, 
* conflicting with * values 
* conflicting with tags from OSM wiki?

**Comment by joto** [comment]
Descriptions from projects only show up in the "projects" tab. The "values" tab only has descriptions from the wiki. It is supposed to be that way.

And please don't use these comments from the old pull request any more. If you have new issues, open a new issue for each of them.

**Pull request merged**
