### PR TITLE
Wrote testing for future PR using Travis CI. Fixes: #18.

### PR DESCRIPTION
**Pull request by ypid**
For each PR the script tests:
* Is the project_list.txt sorted
* Is the ID valid
* Does the URL refer to a valid JSON file

This is how it will look like:
* https://github.com/ypid/taginfo-projects_travis/pulls
* https://travis-ci.org/ypid/taginfo-projects_travis/branches
* https://github.com/ypid/taginfo-projects/tree/added_travis_build#testing

You just need to enable Travis CI for this repository and it should
work.

BTW: @joto Keep up the good work :smile: :+1:

### CODE REVIEW

**Comment by joto** [comment]
This is pretty cool. I have a few remarks:
* Would you consider using GPL v3 for the script? This is the same license used for the rest of taginfo. It is not terribly important, but would keep things simpler.
* Could you use the new docker-based travis? Scripts don't run as root any more so the `apt-get` has to be done differently, but usually travis is much faster at running the scrips. See https://github.com/osmcode/libosmium/blob/master/.travis.yml for an example.
* Consider factoring out the ansi color codes into variables or so. This would make the code easier to read.

**Comment by ypid** [comment]
Nice feedback. Done :smile:

**Comment by joto** [comment]
Sorry, I had already incorporated some changes from you. Could you do a rebase?

**Comment by ypid** [comment]
All right. Done.

**Pull request merged**
